# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'infor[me]' do

pod 'CCBottomRefreshControl'
pod 'Parse'
pod 'ParseUI'
pod 'RKDropdownAlert'
pod 'RSKImageCropper'
pod 'DateTools'

end