//
//  UIColor+Announcements-iOS.swift
//
//  Generated by Zeplin on 8/7/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    class func PrimaryColor() -> UIColor {
        return UIColor(red: 26.0 / 255.0, green: 188.0 / 255.0, blue: 156.0 / 255.0, alpha: 1.0)
    }

    class func AccentColor() -> UIColor {
        return UIColor(red: 233.0 / 255.0, green: 30.0 / 255.0, blue: 99.0 / 255.0, alpha: 1.0)
    }
}
